import { createContext, useContext, useEffect, useMemo, useRef, useState, useCallback, type ReactNode } from "react";

export type BucketId = "wooden" | "large";
export type GadgetId = "magnet" | "slowmo" | "large_bucket" | "shield" | "shockwave" | "golden_heart";
export type GoldenFruitKey = "banana" | "apple" | "coconut";

/** Cosmetic skins applied on top of the wooden bucket. "default" = no skin. */
export type BucketSkinId = "default" | "gold" | "cart" | "teacup" | "ghost";

/** Pet companions that auto-collect grounded fruit. */
export type PetId = "dog" | "cat" | "bunny";

// =============== GARDEN / CAMPAGNA ===============
/** A planted plot in the player's garden. Generated by completing a level. */
export interface GardenPlant {
  id: string;
  /** Source level id (1..N) — drives the fruit shown and yield rate */
  levelId: number;
  plantedAt: number;
}

/** Coins-per-minute by source level. */
export const GARDEN_RATE_BY_LEVEL: Record<number, number> = {
  1: 1, 2: 2, 3: 3, 4: 5,
};
export const GARDEN_MAX_ACCUMULATION_MS = 8 * 60 * 60 * 1000; // 8h
export const GARDEN_MAX_PLOTS = 12;

export function computePlantPending(plant: GardenPlant, lastClaim: number, nowMs: number): number {
  const rate = GARDEN_RATE_BY_LEVEL[plant.levelId] ?? 1;
  const start = Math.max(plant.plantedAt, lastClaim);
  const elapsed = Math.min(GARDEN_MAX_ACCUMULATION_MS, Math.max(0, nowMs - start));
  return Math.floor((elapsed / 60_000) * rate);
}

export interface ShopItemDef {
  id: string;
  kind: "bucket" | "gadget" | "golden_pack" | "skin" | "pet";
  price: number;
  /** Minimum game level required to see/buy this item. */
  requiredLevel?: number;
  // bucket-specific
  bucketId?: BucketId;
  bucketWidth?: number;
  // gadget-specific
  gadgetId?: GadgetId;
  durationMs?: number;
  // skin-specific
  skinId?: BucketSkinId;
  // pet-specific
  petId?: PetId;
}

export const LARGE_BUCKET_DURATION_MS = 5 * 60 * 1000; // 5 minutes
export const SLOWMO_DURATION_MS = 10_000;

export const SHOP_ITEMS: ShopItemDef[] = [
  {
    id: "bucket_large",
    kind: "bucket",
    bucketId: "large",
    bucketWidth: 200,
    durationMs: LARGE_BUCKET_DURATION_MS,
    price: 150,
  },
  {
    id: "gadget_magnet",
    kind: "gadget",
    gadgetId: "magnet",
    durationMs: 30_000,
    price: 80,
  },
  {
    id: "gadget_slowmo",
    kind: "gadget",
    gadgetId: "slowmo",
    durationMs: SLOWMO_DURATION_MS,
    price: 60,
  },
  {
    id: "gadget_shield",
    kind: "gadget",
    gadgetId: "shield",
    price: 100,
  },
  {
    id: "gadget_shockwave",
    kind: "gadget",
    gadgetId: "shockwave",
    price: 120,
  },
  {
    id: "gadget_golden_heart",
    kind: "gadget",
    gadgetId: "golden_heart",
    price: 180,
  },
  {
    /** Single item that unlocks the Golden Fruit drop in EVERY level. */
    id: "golden_pack",
    kind: "golden_pack",
    price: 300,
  },
  // ============== Bucket skins (cosmetic, permanent) ==============
  { id: "skin_default", kind: "skin", skinId: "default", price: 0 },
  { id: "skin_gold", kind: "skin", skinId: "gold", price: 250 },
  { id: "skin_cart", kind: "skin", skinId: "cart", price: 200 },
  { id: "skin_teacup", kind: "skin", skinId: "teacup", price: 220, requiredLevel: 2 },
  { id: "skin_ghost", kind: "skin", skinId: "ghost", price: 280, requiredLevel: 3 },
  // ============== Pets (permanent companions) ==============
  { id: "pet_dog", kind: "pet", petId: "dog", price: 200, requiredLevel: 2 },
  { id: "pet_cat", kind: "pet", petId: "cat", price: 200, requiredLevel: 2 },
  { id: "pet_bunny", kind: "pet", petId: "bunny", price: 280, requiredLevel: 3 },
];

// =============== ACHIEVEMENTS ===============
export interface AchievementDef {
  id: string;
  icon: string;
  /** i18n key for title/description (e.g. ach_first_harvest). */
  key: string;
  /** Reward in coins when unlocked. */
  reward: number;
}

export const ACHIEVEMENTS: AchievementDef[] = [
  { id: "first_harvest", icon: "🌱", key: "ach_first_harvest", reward: 10 },
  { id: "combo_15", icon: "🔥", key: "ach_combo_15", reward: 25 },
  { id: "combo_30", icon: "⚡", key: "ach_combo_30", reward: 75 },
  { id: "combo_50", icon: "💥", key: "ach_combo_50", reward: 200 },
  { id: "golden_10", icon: "✨", key: "ach_golden_10", reward: 50 },
  { id: "golden_100", icon: "👑", key: "ach_golden_100", reward: 250 },
  { id: "level_complete", icon: "🏆", key: "ach_level_complete", reward: 30 },
  { id: "all_levels", icon: "🌍", key: "ach_all_levels", reward: 500 },
  { id: "fruits_500", icon: "🍎", key: "ach_fruits_500", reward: 50 },
  { id: "fruits_5000", icon: "🍇", key: "ach_fruits_5000", reward: 300 },
  { id: "rich_500", icon: "💰", key: "ach_rich_500", reward: 50 },
  { id: "time_attack_50", icon: "⏱️", key: "ach_time_attack_50", reward: 100 },
  { id: "no_drop", icon: "🧚", key: "ach_no_drop", reward: 150 },
  { id: "no_bomb_hit", icon: "🤸", key: "ach_no_bomb_hit", reward: 150 },
];

// =============== DAILY QUESTS ===============
export type QuestKind = "catch_fruits" | "combo" | "catch_golden" | "complete_levels";

export interface QuestDef {
  kind: QuestKind;
  target: number;
  reward: number;
}

export interface ActiveQuest extends QuestDef {
  id: string;
  progress: number;
  done: boolean;
  claimed: boolean;
}

const QUEST_POOL: QuestDef[] = [
  { kind: "catch_fruits", target: 50, reward: 30 },
  { kind: "catch_fruits", target: 150, reward: 80 },
  { kind: "catch_fruits", target: 300, reward: 150 },
  { kind: "combo", target: 1, reward: 40 },
  { kind: "combo", target: 3, reward: 120 },
  { kind: "catch_golden", target: 5, reward: 60 },
  { kind: "catch_golden", target: 20, reward: 200 },
  { kind: "complete_levels", target: 1, reward: 50 },
  { kind: "complete_levels", target: 2, reward: 110 },
];

function rollDailyQuests(seed: string): ActiveQuest[] {
  // Deterministic per day so reload doesn't reroll
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  const pool = [...QUEST_POOL];
  const picked: QuestDef[] = [];
  for (let i = 0; i < 3 && pool.length; i++) {
    h = (h * 1103515245 + 12345) & 0x7fffffff;
    const idx = h % pool.length;
    picked.push(pool.splice(idx, 1)[0]);
  }
  return picked.map((q, i) => ({
    ...q,
    id: `${seed}-${i}`,
    progress: 0,
    done: false,
    claimed: false,
  }));
}

function todayKey() {
  const d = new Date();
  return `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`;
}

interface GameStateValue {
  coins: number;
  addCoins: (n: number) => void;
  spendCoins: (n: number) => boolean;
  ownedBuckets: BucketId[];
  equippedBucket: BucketId;
  equipBucket: (b: BucketId) => void;
  ownsBucket: (b: BucketId) => boolean;
  largeBucketUntil: number;
  largeBucketRemainingMs: number;
  activateLargeBucket: (ms: number) => void;
  deactivateLargeBucket: () => void;
  inventory: Record<GadgetId, number>;
  addGadget: (g: GadgetId, n?: number) => void;
  consumeGadget: (g: GadgetId) => boolean;
  goldenPackOwned: boolean;
  unlockGoldenPack: () => void;
  goldenPackEquipped: boolean;
  equipGoldenPack: () => void;
  unequipGoldenPack: () => void;
  // Bucket skins (cosmetic, applied to wooden bucket)
  ownedSkins: BucketSkinId[];
  equippedSkin: BucketSkinId;
  unlockSkin: (s: BucketSkinId) => void;
  equipSkin: (s: BucketSkinId) => void;
  // Pets
  ownedPets: PetId[];
  equippedPet: PetId | null;
  unlockPet: (p: PetId) => void;
  equipPet: (p: PetId | null) => void;
  // Achievements
  achievements: Record<string, number>; // unlocked timestamp
  unlockAchievement: (id: string) => boolean; // returns true if newly unlocked
  // Stats (for achievement triggers)
  stats: {
    totalFruits: number;
    totalGolden: number;
    totalLevelsDone: number;
    bestCombo: number;
    bestTimeAttack: number;
    perfectNoDropLevels: number;
    perfectNoBombLevels: number;
  };
  bumpStat: (key: keyof GameStateValue["stats"], by?: number) => void;
  setBest: (key: "bestCombo" | "bestTimeAttack", value: number) => void;
  // Daily quests
  quests: ActiveQuest[];
  progressQuest: (kind: QuestKind, by?: number) => void;
  claimQuest: (id: string) => void;
  // Garden / Campagna
  garden: GardenPlant[];
  gardenLastClaim: number;
  plantInGarden: (levelId: number) => boolean;
  claimGardenCoins: () => number;
  computeGardenPending: () => number;
}

const Ctx = createContext<GameStateValue | null>(null);
const STORAGE_KEY = "fruit-harvest-game-v5";

/** TEMP: infinite coins mode for testing. Set to false to restore the economy. */
const INFINITE_COINS = true;
const INFINITE_COINS_VALUE = 999_999;

interface PersistShape {
  coins: number;
  ownedBuckets: BucketId[];
  equippedBucket: BucketId;
  inventory: Record<GadgetId, number>;
  goldenPackOwned: boolean;
  goldenPackEquipped?: boolean;
  largeBucketUntil?: number;
  achievements?: Record<string, number>;
  stats?: GameStateValue["stats"];
  questsDay?: string;
  quests?: ActiveQuest[];
  ownedSkins?: BucketSkinId[];
  equippedSkin?: BucketSkinId;
  ownedPets?: PetId[];
  equippedPet?: PetId | null;
  garden?: GardenPlant[];
  gardenLastClaim?: number;
}

const defaultStats: GameStateValue["stats"] = {
  totalFruits: 0,
  totalGolden: 0,
  totalLevelsDone: 0,
  bestCombo: 0,
  bestTimeAttack: 0,
  perfectNoDropLevels: 0,
  perfectNoBombLevels: 0,
};

export function GameStateProvider({ children }: { children: ReactNode }) {
  const [coins, setCoins] = useState(0);
  const [ownedBuckets, setOwnedBuckets] = useState<BucketId[]>(["wooden"]);
  const [storedEquipped, setStoredEquipped] = useState<BucketId>("wooden");
  const [inventory, setInventory] = useState<Record<GadgetId, number>>({ magnet: 0, slowmo: 0, large_bucket: 0, shield: 0, shockwave: 0, golden_heart: 0 });
  // Mirror inventory in a ref so consumeGadget can make a synchronous, race-free decision
  // (React 18 may defer setState updaters; relying on the updater's return value to know
  // whether stock existed leaks into a "click does nothing" bug). The ref is the truth
  // for "do I have stock right now"; setInventory still drives renders.
  const inventoryRef = useRef(inventory);
  useEffect(() => { inventoryRef.current = inventory; }, [inventory]);
  const [goldenPackOwned, setGoldenPackOwned] = useState(false);
  const [goldenPackEquipped, setGoldenPackEquipped] = useState(false);
  const [largeBucketUntil, setLargeBucketUntil] = useState(0);
  const [now, setNow] = useState(() => (typeof window !== "undefined" ? Date.now() : 0));
  const [hydrated, setHydrated] = useState(false);
  const [achievements, setAchievements] = useState<Record<string, number>>({});
  const [stats, setStats] = useState<GameStateValue["stats"]>(defaultStats);
  const [quests, setQuests] = useState<ActiveQuest[]>([]);
  const [questsDay, setQuestsDay] = useState<string>("");
  const [ownedSkins, setOwnedSkins] = useState<BucketSkinId[]>(["default"]);
  const [equippedSkin, setEquippedSkin] = useState<BucketSkinId>("default");
  const [ownedPets, setOwnedPets] = useState<PetId[]>([]);
  const [equippedPet, setEquippedPet] = useState<PetId | null>(null);
  const [garden, setGarden] = useState<GardenPlant[]>([]);
  const [gardenLastClaim, setGardenLastClaim] = useState<number>(() =>
    typeof window !== "undefined" ? Date.now() : 0,
  );

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw) as Partial<PersistShape>;
        setCoins(INFINITE_COINS ? INFINITE_COINS_VALUE : (parsed.coins ?? 0));
        setOwnedBuckets(parsed.ownedBuckets ?? ["wooden"]);
        setStoredEquipped(parsed.equippedBucket === "large" ? "wooden" : (parsed.equippedBucket ?? "wooden"));
        setInventory({ magnet: 0, slowmo: 0, large_bucket: 0, shield: 0, shockwave: 0, golden_heart: 0, ...(parsed.inventory ?? {}) });
        setGoldenPackOwned(parsed.goldenPackOwned ?? false);
        setGoldenPackEquipped(parsed.goldenPackEquipped ?? (parsed.goldenPackOwned ?? false));
        setLargeBucketUntil(parsed.largeBucketUntil ?? 0);
        setAchievements(parsed.achievements ?? {});
        setStats({ ...defaultStats, ...(parsed.stats ?? {}) });
        // Skins & pets
        const persistedSkins = parsed.ownedSkins ?? ["default"];
        setOwnedSkins(persistedSkins.includes("default") ? persistedSkins : ["default", ...persistedSkins]);
        setEquippedSkin(parsed.equippedSkin ?? "default");
        setOwnedPets(parsed.ownedPets ?? []);
        setEquippedPet(parsed.equippedPet ?? null);
        setGarden(parsed.garden ?? []);
        setGardenLastClaim(parsed.gardenLastClaim ?? Date.now());
        // quests: refresh if day changed
        const today = todayKey();
        if (parsed.questsDay === today && parsed.quests) {
          setQuests(parsed.quests);
          setQuestsDay(today);
        } else {
          setQuests(rollDailyQuests(today));
          setQuestsDay(today);
        }
      } else {
        const today = todayKey();
        setQuests(rollDailyQuests(today));
        setQuestsDay(today);
      }
    } catch {
      // ignore
    }
    setHydrated(true);
  }, []);

  // Daily refresh checker (poll every minute)
  useEffect(() => {
    const id = window.setInterval(() => {
      const today = todayKey();
      if (today !== questsDay) {
        setQuests(rollDailyQuests(today));
        setQuestsDay(today);
      }
    }, 60_000);
    return () => clearInterval(id);
  }, [questsDay]);

  useEffect(() => {
    if (largeBucketUntil === 0) return;
    const id = window.setInterval(() => {
      const t = Date.now();
      setNow(t);
      if (t >= largeBucketUntil) {
        setLargeBucketUntil(0);
      }
    }, 1000);
    return () => clearInterval(id);
  }, [largeBucketUntil]);

  const largeActive = largeBucketUntil > now;
  const equippedBucket: BucketId = largeActive ? "large" : storedEquipped;
  const largeBucketRemainingMs = largeActive ? largeBucketUntil - now : 0;

  useEffect(() => {
    if (!hydrated) return;
    if (typeof window === "undefined") return;
    try {
      const data: PersistShape = {
        coins,
        ownedBuckets,
        equippedBucket: storedEquipped,
        inventory,
        goldenPackOwned,
        goldenPackEquipped,
        largeBucketUntil,
        achievements,
        stats,
        questsDay,
        quests,
        ownedSkins,
        equippedSkin,
        ownedPets,
        equippedPet,
        garden,
        gardenLastClaim,
      };
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch {
      // ignore
    }
  }, [coins, ownedBuckets, storedEquipped, inventory, goldenPackOwned, goldenPackEquipped, largeBucketUntil, achievements, stats, questsDay, quests, ownedSkins, equippedSkin, ownedPets, equippedPet, garden, gardenLastClaim, hydrated]);

  const addCoins = useCallback((n: number) => {
    if (INFINITE_COINS) {
      setCoins(INFINITE_COINS_VALUE);
      return;
    }
    setCoins((c) => Math.max(0, c + n));
  }, []);

  const spendCoins = useCallback((n: number) => {
    if (INFINITE_COINS) {
      setCoins(INFINITE_COINS_VALUE);
      return true;
    }
    let ok = false;
    setCoins((c) => {
      if (c >= n) {
        ok = true;
        return c - n;
      }
      return c;
    });
    return ok;
  }, []);

  const equipBucket = useCallback((b: BucketId) => {
    if (b === "large") return;
    setStoredEquipped(b);
  }, []);

  const ownsBucket = useCallback(
    (b: BucketId) => ownedBuckets.includes(b),
    [ownedBuckets],
  );

  const activateLargeBucket = useCallback((ms: number) => {
    const base = Math.max(Date.now(), largeBucketUntil);
    setLargeBucketUntil(base + ms);
    setNow(Date.now());
  }, [largeBucketUntil]);

  const deactivateLargeBucket = useCallback(() => {
    setLargeBucketUntil(0);
    setNow(Date.now());
  }, []);

  const addGadget = useCallback((g: GadgetId, n = 1) => {
    const next = { ...inventoryRef.current, [g]: (inventoryRef.current[g] ?? 0) + n };
    inventoryRef.current = next;
    setInventory(next);
  }, []);

  const consumeGadget = useCallback((g: GadgetId) => {
    const current = inventoryRef.current[g] ?? 0;
    if (current <= 0) return false;
    // Decrement the ref synchronously so rapid double-clicks can't both succeed
    // off the same stock count.
    inventoryRef.current = { ...inventoryRef.current, [g]: current - 1 };
    setInventory(inventoryRef.current);
    return true;
  }, []);

  const unlockGoldenPack = useCallback(() => {
    setGoldenPackOwned(true);
    setGoldenPackEquipped(true);
  }, []);

  const equipGoldenPack = useCallback(() => {
    setGoldenPackEquipped(true);
  }, []);

  const unequipGoldenPack = useCallback(() => {
    setGoldenPackEquipped(false);
  }, []);

  const unlockSkin = useCallback((s: BucketSkinId) => {
    setOwnedSkins((prev) => (prev.includes(s) ? prev : [...prev, s]));
  }, []);

  const equipSkin = useCallback((s: BucketSkinId) => {
    setEquippedSkin(s);
  }, []);

  const unlockPet = useCallback((p: PetId) => {
    setOwnedPets((prev) => (prev.includes(p) ? prev : [...prev, p]));
    setEquippedPet((curr) => curr ?? p);
  }, []);

  const equipPet = useCallback((p: PetId | null) => {
    setEquippedPet(p);
  }, []);

  const unlockAchievement = useCallback((id: string) => {
    let isNew = false;
    setAchievements((a) => {
      if (a[id]) return a;
      isNew = true;
      return { ...a, [id]: Date.now() };
    });
    if (isNew) {
      const def = ACHIEVEMENTS.find((x) => x.id === id);
      if (def) {
        setCoins((c) => c + def.reward);
      }
    }
    return isNew;
  }, []);

  const bumpStat = useCallback((key: keyof GameStateValue["stats"], by = 1) => {
    setStats((s) => ({ ...s, [key]: (s[key] ?? 0) + by }));
  }, []);

  const setBest = useCallback((key: "bestCombo" | "bestTimeAttack", value: number) => {
    setStats((s) => ({ ...s, [key]: Math.max(s[key] ?? 0, value) }));
  }, []);

  const progressQuest = useCallback((kind: QuestKind, by = 1) => {
    setQuests((qs) =>
      qs.map((q) => {
        if (q.kind !== kind || q.done) return q;
        const next = Math.min(q.target, q.progress + by);
        return { ...q, progress: next, done: next >= q.target };
      }),
    );
  }, []);

  const claimQuest = useCallback((id: string) => {
    setQuests((qs) =>
      qs.map((q) => {
        if (q.id !== id || !q.done || q.claimed) return q;
        setCoins((c) => c + q.reward);
        return { ...q, claimed: true };
      }),
    );
  }, []);

  // ============== Garden actions ==============
  const plantInGarden = useCallback((levelId: number) => {
    let placed = false;
    setGarden((g) => {
      if (g.length >= GARDEN_MAX_PLOTS) return g;
      placed = true;
      return [
        ...g,
        { id: `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, levelId, plantedAt: Date.now() },
      ];
    });
    return placed;
  }, []);

  const computeGardenPending = useCallback(() => {
    const nowMs = Date.now();
    return garden.reduce((sum, p) => sum + computePlantPending(p, gardenLastClaim, nowMs), 0);
  }, [garden, gardenLastClaim]);

  const claimGardenCoins = useCallback(() => {
    const nowMs = Date.now();
    const total = garden.reduce((sum, p) => sum + computePlantPending(p, gardenLastClaim, nowMs), 0);
    if (total > 0) {
      setCoins((c) => c + total);
      setGardenLastClaim(nowMs);
    }
    return total;
  }, [garden, gardenLastClaim]);

  const value = useMemo<GameStateValue>(
    () => ({
      coins,
      addCoins,
      spendCoins,
      ownedBuckets,
      equippedBucket,
      equipBucket,
      ownsBucket,
      largeBucketUntil,
      largeBucketRemainingMs,
      activateLargeBucket,
      deactivateLargeBucket,
      inventory,
      addGadget,
      consumeGadget,
      goldenPackOwned,
      unlockGoldenPack,
      goldenPackEquipped,
      equipGoldenPack,
      unequipGoldenPack,
      ownedSkins,
      equippedSkin,
      unlockSkin,
      equipSkin,
      ownedPets,
      equippedPet,
      unlockPet,
      equipPet,
      achievements,
      unlockAchievement,
      stats,
      bumpStat,
      setBest,
      quests,
      progressQuest,
      claimQuest,
      garden,
      gardenLastClaim,
      plantInGarden,
      claimGardenCoins,
      computeGardenPending,
    }),
    [
      coins,
      ownedBuckets,
      equippedBucket,
      largeBucketUntil,
      largeBucketRemainingMs,
      inventory,
      goldenPackOwned,
      goldenPackEquipped,
      ownedSkins,
      equippedSkin,
      ownedPets,
      equippedPet,
      achievements,
      stats,
      quests,
      garden,
      gardenLastClaim,
      addCoins,
      spendCoins,
      equipBucket,
      ownsBucket,
      activateLargeBucket,
      addGadget,
      consumeGadget,
      unlockGoldenPack,
      equipGoldenPack,
      unequipGoldenPack,
      unlockSkin,
      equipSkin,
      unlockPet,
      equipPet,
      unlockAchievement,
      bumpStat,
      setBest,
      progressQuest,
      claimQuest,
      plantInGarden,
      claimGardenCoins,
      computeGardenPending,
    ],
  );

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useGameState() {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error("useGameState must be used inside GameStateProvider");
  return ctx;
}

export const BUCKET_WIDTHS: Record<BucketId, number> = {
  wooden: 140,
  large: 200,
};
